server.port: 9001
spring:
  application:
    name: project-api
  mvc:
    pathmatch:
      use-trailing-slash: true

appkey:
  location: secret-keys/setcret-keys

logging:
  config: classpath:log4j2/log4j2-local.xml